{
 "title": "Grafana_antifraud_custom_metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Http_server_requests_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    }
   ]
  },
  {
   "title": "Spring_data_repository_invocations_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_count"
    }
   ]
  },
  {
   "title": "Http_server_requests_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum"
    }
   ]
  },
  {
   "title": "Spring_data_repository_invocations_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_sum"
    }
   ]
  },
  {
   "title": "Http_server_requests_seconds_max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max"
    }
   ]
  },
  {
   "title": "Spring_data_repository_invocations_seconds_max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_max"
    }
   ]
  }
 ]
}